#runtime: python39
#
#instance_class: F2
#
#entrypoint: gunicorn -b :$PORT your_app_module:app
#
#handlers:
#- url: /static
#  static_dir: static
#
#- url: /.*
#  script: auto
#
#env_variables:
#  KEY: 'value'
#
#automatic_scaling:
#  target_cpu_utilization: 0.65
#  target_throughput_utilization: 0.65